development:
  adapter:  postgresql
  host:     192.168.35.155
  encoding: unicode
  database: elidom_dev
  username: postgres
  password: 1
  template: template0
  pool:     5
test:
  adapter:  postgresql
  host:     192.168.35.155
  encoding: unicode
  database: elidom_dev
  username: postgres
  password: 1
  template: template0
  pool:     5
production:
  adapter:  postgresql
  host:     192.168.35.155
  encoding: unicode
  database: elidom_dev
  username: postgres
  password: 1
  template: template0
  pool:     5
